# Generated by Django 3.0.3 on 2020-05-08 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 17, 33, 13, 217134), verbose_name='date published'),
        ),
    ]
